#!/bin/bash
# Knowledge Repository 帮助脚本
# 显示所有可用脚本及其用法

echo "=========================================="
echo "  Knowledge Repository 脚本工具集"
echo "=========================================="
echo ""

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== 服务管理 ==="
echo "  start.sh          - 启动服务"
echo "  stop.sh           - 停止服务"
echo "  restart.sh        - 重启服务"
echo "  status.sh         - 查看服务状态"
echo "  logs.sh [行数]    - 查看日志"
echo ""

echo "=== 部署运维 ==="
echo "  deploy.sh         - 一键部署完整环境"
echo "  env-check.sh      - 环境检查"
echo "  health-check.sh   - 健康检查"
echo "  docker-build.sh   - 构建 Docker 镜像"
echo "  compose.sh [cmd]  - Docker Compose 管理"
echo ""

echo "=== 数据管理 ==="
echo "  backup.sh         - 数据备份"
echo "  export.sh         - 导出数据"
echo "  import.sh <文件>  - 导入数据"
echo "  init-db.sh        - 初始化数据库 (危险!)"
echo "  clean.sh          - 清理临时文件"
echo ""

echo "=== 业务管理 ==="
echo "  doc.sh [cmd]      - 文档管理"
echo "  user.sh [cmd]     - 用户管理"
echo "  dept.sh [cmd]     - 部门管理"
echo "  role.sh [cmd]     - 角色权限管理"
echo "  config.sh [cmd]   - 系统配置管理"
echo "  search.sh [cmd]   - 搜索管理"
echo ""

echo "=== 监控诊断 ==="
echo "  monitor.sh        - 服务监控"
echo "  metrics.sh [cmd]  - 监控指标"
echo "  perf.sh [cmd]     - 性能分析"
echo "  disk-usage.sh     - 磁盘使用分析"
echo "  network.sh [cmd]  - 网络诊断"
echo "  report.sh         - 生成系统报告"
echo ""

echo "=== 安全审计 ==="
echo "  security.sh [cmd] - 安全管理"
echo "  audit.sh [cmd]    - 审计日志"
echo "  session.sh [cmd]  - 会话管理"
echo ""

echo "=== 高级功能 ==="
echo "  apikey.sh [cmd]   - API Key 管理"
echo "  webhook.sh [cmd]  - Webhook 管理"
echo "  schedule.sh [cmd] - 定时任务管理"
echo "  notify.sh [cmd]   - 通知管理"
echo "  plugin.sh [cmd]   - 插件管理"
echo "  theme.sh [cmd]    - 主题管理"
echo "  cache.sh [cmd]    - 缓存管理"
echo "  ratelimit.sh      - 限流配置"
echo "  task.sh [cmd]     - 异步任务管理"
echo ""

echo "=== 调试排错 ==="
echo "  debug.sh [cmd]    - 调试工具"
echo "  troubleshoot.sh   - 故障排查"
echo "  log.sh [cmd]      - 日志管理"
echo "  api-test.sh       - API 测试"
echo ""

echo "=========================================="
echo "使用示例:"
echo "=========================================="
echo ""
echo "  启动服务:       ./scripts/start.sh"
echo "  查看状态:       ./scripts/status.sh"
echo "  查看日志:       ./scripts/logs.sh 200"
echo "  文档列表:       ./scripts/doc.sh list"
echo "  搜索知识库:     ./scripts/search.sh query '关键词'"
echo "  健康检查:       ./scripts/health-check.sh"
echo "  数据备份:       ./scripts/backup.sh"
echo "  故障排查:       ./scripts/troubleshoot.sh check"
echo ""
echo "每个脚本都有内置帮助，使用 ./scripts/<脚本>.sh 查看用法"
echo ""
